2021-02-16 11:14:53,085 INFO    MainThread:8819 [wandb_setup.py:_flush():70] setting env: {}
2021-02-16 11:14:53,086 INFO    MainThread:8819 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-02-16 11:14:53,086 INFO    MainThread:8819 [wandb_setup.py:_flush():70] setting login settings: {}
2021-02-16 11:14:53,086 INFO    MainThread:8819 [wandb_setup.py:_flush():70] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f93c08701c0>
2021-02-16 11:14:53,086 INFO    MainThread:8819 [wandb_init.py:_log_setup():319] Logging user logs to /home/johannbs/Desktop/IceCube_GNN/wandb/run-20210216_111453-2rvji946/logs/debug.log
2021-02-16 11:14:53,087 INFO    MainThread:8819 [wandb_init.py:_log_setup():320] Logging internal logs to /home/johannbs/Desktop/IceCube_GNN/wandb/run-20210216_111453-2rvji946/logs/debug-internal.log
2021-02-16 11:14:53,087 INFO    MainThread:8819 [wandb_init.py:init():351] calling init triggers
2021-02-16 11:14:53,087 INFO    MainThread:8819 [wandb_init.py:init():356] wandb.init called with sweep_config: {}
config: {}
2021-02-16 11:14:53,087 INFO    MainThread:8819 [wandb_init.py:init():404] starting backend
2021-02-16 11:14:53,097 INFO    MainThread:8819 [backend.py:ensure_launched():81] starting backend process...
2021-02-16 11:14:53,103 INFO    MainThread:8819 [backend.py:ensure_launched():85] started backend process with pid: 8837
2021-02-16 11:14:53,104 INFO    MainThread:8819 [wandb_init.py:init():413] backend started and connected
2021-02-16 11:14:53,105 INFO    MainThread:8819 [wandb_init.py:init():436] updated telemetry
2021-02-16 11:14:53,106 INFO    MainThread:8819 [wandb_init.py:init():459] communicating current version
2021-02-16 11:14:53,832 INFO    MainThread:8819 [wandb_init.py:init():464] got version response 
2021-02-16 11:14:53,832 INFO    MainThread:8819 [wandb_init.py:init():472] communicating run to backend with 30 second timeout
2021-02-16 11:14:54,037 INFO    MainThread:8819 [wandb_init.py:init():495] starting run threads in backend
2021-02-16 11:14:55,414 INFO    MainThread:8819 [wandb_run.py:_console_start():1411] atexit reg
2021-02-16 11:14:55,415 INFO    MainThread:8819 [wandb_run.py:_redirect():1274] redirect: SettingsConsole.WRAP
2021-02-16 11:14:55,415 INFO    MainThread:8819 [wandb_run.py:_redirect():1309] Wrapping output streams.
2021-02-16 11:14:55,415 INFO    MainThread:8819 [wandb_run.py:_redirect():1325] Redirects installed.
2021-02-16 11:14:55,415 INFO    MainThread:8819 [wandb_init.py:init():518] run started, returning control to user process
2021-02-16 11:14:56,264 INFO    MainThread:8819 [wandb_config.py:__setitem__():142] config set hidden_states = 64 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7f93b8842a00>>
2021-02-16 11:14:56,264 INFO    MainThread:8819 [wandb_run.py:_config_callback():663] config_cb hidden_states 64 None
2021-02-16 11:14:56,264 INFO    MainThread:8819 [wandb_config.py:__setitem__():142] config set forward = False - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7f93b8842a00>>
2021-02-16 11:14:56,264 INFO    MainThread:8819 [wandb_run.py:_config_callback():663] config_cb forward False None
2021-02-16 11:14:56,264 INFO    MainThread:8819 [wandb_config.py:__setitem__():142] config set dropout = 0 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7f93b8842a00>>
2021-02-16 11:14:56,265 INFO    MainThread:8819 [wandb_run.py:_config_callback():663] config_cb dropout 0 None
2021-02-16 11:15:05,730 INFO    MainThread:8819 [wandb_init.py:_pause_backend():240] pausing backend
2021-02-16 11:15:47,875 INFO    MainThread:8819 [wandb_init.py:_resume_backend():245] resuming backend
2021-02-16 11:15:47,875 INFO    MainThread:8819 [wandb_init.py:_pause_backend():240] pausing backend
2021-02-16 11:15:47,876 INFO    MainThread:8819 [wandb_run.py:_atexit_cleanup():1381] got exitcode: 0
2021-02-16 11:15:47,877 INFO    MainThread:8819 [wandb_run.py:_restore():1353] restore
2021-02-16 11:15:48,103 INFO    MainThread:8819 [wandb_run.py:_wait_for_finish():1504] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 790
  total_bytes: 790
}

2021-02-16 11:15:50,106 INFO    MainThread:8819 [wandb_run.py:_wait_for_finish():1504] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 15391
  total_bytes: 15391
}

2021-02-16 11:15:51,386 INFO    MainThread:8819 [wandb_run.py:_show_files():1726] logging synced files
